version: '3.3'

services:
  fastapi:
    image: chatgpt-interviewer-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt_chatbot_fastapi
    env_file:
      - .env
    ports:
      - 3000:3000
