name: FastAPI Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nicolasmura/chatgpt-interviewer-bot:latest
          secrets: |
            "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}"
            "OPEN_AI_ORG=${{ secrets.OPEN_AI_ORG }}"
            "ELEVENLABS_KEY=${{ secrets.ELEVENLABS_KEY }}"
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1

  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to Docker Hub
  #       run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

  #     - name: Build and push Docker image
  #       run: |
  #         docker buildx create --use
  #         docker buildx build \
  #           --file Dockerfile \
  #           --tag nicolasmura/chatgpt-interviewer-bot:latest \
  #           --push .

  #   env:
  #     DOCKER_CLI_EXPERIMENTAL: enabled
  #     DOCKER_BUILDKIT: 1
