name: FastAPI Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file
        run: |
          touch .env
          echo OPEN_AI_KEY=${OPEN_AI_KEY} >> .env
          echo OPEN_AI_ORG=${OPEN_AI_ORG} >> .env
          echo ELEVENLABS_KEY=${ELEVENLABS_KEY} >> .env
          cat .env
        env:
          OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
          OPEN_AI_ORG: ${{ secrets.OPEN_AI_ORG }}
          ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}'
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nicolasmura/chatgpt-interviewer-bot:latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
