name: FastAPI Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    steps:
      - uses: actions/checkout@v3

      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: path/to/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: hub.docker.com/chatgpt-interviewer-bot:latest
          secrets: |
            "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}"
            "OPEN_AI_ORG=${{ secrets.OPEN_AI_ORG }}"
            "ELEVENLABS_KEY=${{ secrets.ELEVENLABS_KEY }}"

    # build:
    #   runs-on: ubuntu-latest

    #   steps:
    #     - name: Checkout code
    #       uses: actions/checkout@v2

    #     - name: Set up Docker Buildx
    #       uses: docker/setup-buildx-action@v1

    #     - name: Login to Docker Hub
    #       run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    #     - name: Build and push Docker image
    #       run: |
    #         docker buildx create --use
    #         docker buildx build \
    #           --file Dockerfile \
    #           --tag nicolasmura/chatgpt-interviewer-bot:latest \
    #           --push .

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
